---

- name: Install Postgresql directory
  file: path=/opt/data/pgsql state=directory

- name: Install Postgresql
  yum: name={{ item }} state=present
  with_items:
    - postgresql-server
    - postgresql-devel

- name: Postgresql data dir
  file: path=/opt/data/pgsql/data state=directory owner=postgres group=postgres

- name: Check if Postgresql is already initialized
  stat: path=/opt/data/pgsql/data/pg_log
  register: pg_init

- name: Init Postgresql database
  command: /usr/bin/initdb -D /opt/data/pgsql/data
  sudo_user: postgres
  when: pg_init.stat.exists == False

- name: Set Postgresql data directory to startup script
  lineinfile: dest=/usr/lib/systemd/system/postgresql.service regexp="^Environment=PGDATA=/var/lib/pgsql/data" line="Environment=PGDATA=/opt/data/pgsql/data"

- name: Enable Postgresql
  service: name=postgresql state=started enabled=yes
